include:
  - project: "infrastructure/gitlab-ci"
    ref: main
    file: "/templates/cloudbuild-common.gitlab-ci.yaml"
  - project: "infrastructure/gitlab-ci"
    ref: main
    file: "templates/deploy.gitlab-ci.yaml"

stages:
  - cloudbuild
  - deploy

cloudbuild:image:master:
  only:
    - master
  except:
    - tags
  extends: .cloudbuild:common

deploy:master:
  only:
    - master
  except:
    - tags
  extends: .deploy
  environment:
    name: stage

stop:master:
  only:
    - master
  except:
    - tags
  extends: .stop
  environment:
    name: stage
